// skeletons/angular-skeleton/src/app/app.component.ts
import { Component } from '@angular/core';
import { WelcomeComponent } from './components/welcome.component';

@Component({
  selector: 'app-root',
  imports: [WelcomeComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'Angular Skeleton Application';
}

<div class="app-container">
  <header class="app-header">
    <h1>{{ title }}</h1>
    <p class="subtitle">Built with Angular 20 + TypeScript</p>
  </header>

  <main class="app-main">
    <app-welcome message="Welcome to your new Angular application!" />

    <div class="info-card">
      <h2>Ready to Build</h2>
      <p>
        This skeleton application is ready for you to add components,
        routes, and functionality. Use AI-assisted development tools
        to rapidly build your application.
      </p>
    </div>

    <div class="getting-started">
      <h3>Getting Started</h3>
      <ul>
        <li>Edit <code>src/app/app.component.html</code> to modify this page</li>
        <li>Create new components in <code>src/app/components/</code></li>
        <li>Add styles in <code>src/app/</code> component CSS files</li>
        <li>Hot module replacement is enabled for instant updates</li>
      </ul>
    </div>
  </main>

  <footer class="app-footer">
    <p>Edit components to see changes instantly with live reload</p>
  </footer>
</div>

// skeletons/frontend/nextjs-skeleton/src/app/page.tsx
import Welcome from "@/components/Welcome";
import styles from "./page.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <svg
          className={styles.logo}
          viewBox="0 0 180 180"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <mask
            id="mask0"
            style={{ maskType: "alpha" }}
            maskUnits="userSpaceOnUse"
            x="0"
            y="0"
            width="180"
            height="180"
          >
            <circle cx="90" cy="90" r="90" fill="black" />
          </mask>
          <g mask="url(#mask0)">
            <circle cx="90" cy="90" r="90" fill="black" />
            <path
              d="M149.508 157.52L69.142 54H54V125.97H66.1136V69.3836L139.999 164.845C143.333 162.614 146.509 160.165 149.508 157.52Z"
              fill="url(#paint0_linear)"
            />
            <rect
              x="115"
              y="54"
              width="12"
              height="72"
              fill="url(#paint1_linear)"
            />
          </g>
          <defs>
            <linearGradient
              id="paint0_linear"
              x1="109"
              y1="116.5"
              x2="144.5"
              y2="160.5"
              gradientUnits="userSpaceOnUse"
            >
              <stop stopColor="white" />
              <stop offset="1" stopColor="white" stopOpacity="0" />
            </linearGradient>
            <linearGradient
              id="paint1_linear"
              x1="121"
              y1="54"
              x2="120.799"
              y2="106.875"
              gradientUnits="userSpaceOnUse"
            >
              <stop stopColor="white" />
              <stop offset="1" stopColor="white" stopOpacity="0" />
            </linearGradient>
          </defs>
        </svg>
        <h1>Next.js Skeleton Application</h1>
        <p className={styles.subtitle}>Built with Next.js + TypeScript</p>
      </header>

      <main className={styles.main}>
        <Welcome message="Welcome to your new Next.js application!" />

        <div className={styles.infoCard}>
          <h2>Ready to Build</h2>
          <p>
            This skeleton application is ready for you to add pages, components,
            and API routes. Use AI-assisted development tools to rapidly build
            your application.
          </p>
        </div>

        <div className={styles.gettingStarted}>
          <h3>Getting Started</h3>
          <ul>
            <li>
              Edit <code>src/app/page.tsx</code> to modify this page
            </li>
            <li>
              Create new pages in <code>src/app/</code> using the App Router
            </li>
            <li>
              Add components in <code>src/components/</code>
            </li>
            <li>
              Add API routes in <code>src/app/api/</code>
            </li>
            <li>Fast Refresh is enabled for instant updates</li>
          </ul>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Edit pages and components to see changes instantly with Fast Refresh</p>
      </footer>
    </div>
  );
}
