// skeletons/frontend/nextjs-skeleton/src/components/Welcome.tsx
"use client";

import { useState } from "react";
import styles from "./Welcome.module.css";

interface WelcomeProps {
  message: string;
}

export default function Welcome({ message }: WelcomeProps) {
  const [count, setCount] = useState(0);

  return (
    <div className={styles.card}>
      <h2>{message}</h2>
      <div className={styles.counterSection}>
        <p>This is a sample interactive component demonstrating React hooks.</p>
        <button
          className={styles.counterButton}
          onClick={() => setCount((c) => c + 1)}
        >
          You clicked {count} {count === 1 ? "time" : "times"}
        </button>
        {count > 0 && (
          <p className={styles.counterMessage}>
            {count >= 10
              ? "Wow, you really like clicking!"
              : "Keep clicking..."}
          </p>
        )}
      </div>
    </div>
  );
}

// skeletons/angular-skeleton/src/app/components/welcome.component.ts
import { Component, Input, signal } from '@angular/core';

@Component({
  selector: 'app-welcome',
  imports: [],
  templateUrl: './welcome.component.html',
  styleUrl: './welcome.component.css'
})
export class WelcomeComponent {
  @Input() message: string = 'Welcome!';

  // Using Angular signals for reactive state management
  count = signal(0);

  incrementCount() {
    this.count.update(value => value + 1);
  }
}

<div class="welcome-card">
  <h2>{{ message }}</h2>
  <div class="counter-section">
    <p>This is a sample interactive component demonstrating Angular signals.</p>
    <button class="counter-button" (click)="incrementCount()">
      You clicked {{ count() }} {{ count() === 1 ? 'time' : 'times' }}
    </button>
    @if (count() > 0) {
      <p class="counter-message">
        @if (count() >= 10) {
          Wow, you really like clicking!
        } @else {
          Keep clicking to see what happens!
        }
      </p>
    }
  </div>
</div>
