// skeletons/react-skeleton/src/components/Welcome.tsx
import { useState } from 'react'

interface WelcomeProps {
  message: string
}

function Welcome({ message }: WelcomeProps) {
  const [count, setCount] = useState(0)

  return (
    <div className="welcome-card">
      <h2>{message}</h2>
      <div className="counter-section">
        <p>This is a sample interactive component demonstrating React hooks.</p>
        <button
          className="counter-button"
          onClick={() => setCount((count) => count + 1)}
        >
          You clicked {count} {count === 1 ? 'time' : 'times'}
        </button>
        {count > 0 && (
          <p className="counter-message">
            {count >= 10
              ? "Wow, you really like clicking!"
              : "Keep clicking to see what happens!"}
          </p>
        )}
      </div>
    </div>
  )
}

export default Welcome

// skeletons/angular-skeleton/src/app/components/welcome.component.ts
import { Component, Input, signal } from '@angular/core';

@Component({
  selector: 'app-welcome',
  imports: [],
  templateUrl: './welcome.component.html',
  styleUrl: './welcome.component.css'
})
export class WelcomeComponent {
  @Input() message: string = 'Welcome!';

  // Using Angular signals for reactive state management
  count = signal(0);

  incrementCount() {
    this.count.update(value => value + 1);
  }
}

<div class="welcome-card">
  <h2>{{ message }}</h2>
  <div class="counter-section">
    <p>This is a sample interactive component demonstrating Angular signals.</p>
    <button class="counter-button" (click)="incrementCount()">
      You clicked {{ count() }} {{ count() === 1 ? 'time' : 'times' }}
    </button>
    @if (count() > 0) {
      <p class="counter-message">
        @if (count() >= 10) {
          Wow, you really like clicking!
        } @else {
          Keep clicking to see what happens!
        }
      </p>
    }
  </div>
</div>
